version: "3.9"

services:
  postgres:
    container_name: agendamed-postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: "/data/postgres"
    volumes:
      - ./data/postgres:/data/postgres
  mongodb:
    container_name: agendamed-mongodb
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./data/mongodb:/data/db
  redis:
    container_name: agendamed-redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
